// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CreateTodo(arg1:services.Todo):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetTodos():Promise<Array<services.Todo>>;

export function UpdateTodo(arg1:number,arg2:services.Todo):Promise<void>;
