// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTodo(arg1) {
  return window['go']['services']['TodoService']['CreateTodo'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['services']['TodoService']['DeleteTodo'](arg1);
}

export function GetTodos() {
  return window['go']['services']['TodoService']['GetTodos']();
}

export function UpdateTodo(arg1, arg2) {
  return window['go']['services']['TodoService']['UpdateTodo'](arg1, arg2);
}
